# Generated by Django 3.2 on 2023-04-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='数据名')),
                ('pub_date', models.DateField(null=True, verbose_name='发布日期')),
                ('readcount', models.IntegerField(default=0, verbose_name='阅读量')),
                ('commentcount', models.IntegerField(default=0, verbose_name='评论数')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否下架')),
            ],
            options={
                'verbose_name': '书籍管理',
                'db_table': 'bookInfo',
            },
        ),
    ]
