# Generated by Django 3.2 on 2023-04-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_peopleinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peopleinfo',
            options={'verbose_name': '人物'},
        ),
        migrations.AlterModelTable(
            name='peopleinfo',
            table='peopleInfo',
        ),
    ]
